export const categories = [
    'Strings',
    'Algorithms',
    'Data Structures',
    'Bit Manipulation',
    'Recursion',
    'Databases',
    'Brainteaser',
    'Arrays',
    'Sorting',
    'Trees',
    'Graphs',
    'Dynamic Programming',
    'Object Oriented Programming',
    'Functional Programming',
    'Operating Systems',
    'Networking',
    'System Design',
    'Security',
    'Testing',
    'Math',
    'Hardware',
    'Software Engineering',
    'Miscellaneous'
  ];